import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home() {
   const [token, setToken] = useState("");
   const [title, setTitle] = useState("");
   const [message, setMessage] = useState("");

   async function pushToken() {
      const MainData = {
         to: token,
         title: title,
         message: message,
         data: { someData: "goes here" },
      };

      // https://exp.host/--/api/v2/push/send

      // send post request with axois
      await axios
         .post("http://localhost:3000/api/notifications", MainData, {
            headers: {
               Accept: "application/json",
               "Accept-encoding": "gzip, deflate",
               "Content-Type": "application/json",
            },
         })
         .then(function (response) {
            console.log(response.data);
         });
   }

   return (
      <div className={styles.container}>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <div className={styles.formbox}>
            <input
               onChange={(e) => setToken(e.target.value)}
               type="text"
               placeholder="enter push token"
            />
            <input
               onChange={(e) => setTitle(e.target.value)}
               type="text"
               placeholder="title"
            />
            <textarea
               onChange={(e) => setMessage(e.target.value)}
               type="text"
               placeholder={"Enter your message"}
            ></textarea>
            <button onClick={pushToken}>Send</button>
            <div>{message}</div>
         </div>
      </div>
   );
}
